### ISSUE TITLE
[BUG] Spell Roll Healing Not Triggering Any Debug Logs

### ISSUE THREAD

**Issue by ChasarooniZ** [MrVauxs/pf2e-graphics#124] opened 2024-08-28 06:02 UTC
![image](https://github.com/user-attachments/assets/efd9ca06-3d60-4047-9c7e-e5b06a3396a2)

### Repeating
Example as shown in the image
- Cast Lay On Hands
- Select Healing
- Roll Healing

### Issue
The only logged data is for when i apply the effect for `effect` and `toggle` however i'd expect to also see a log for
- `Spell Cast`
- `Damage Roll`

**Comment by MrVauxs** [comment] 2024-08-28 09:39
The spell not triggering `spell-cast` is a duplicate of #120 
Will look into the damage roll.

**Comment by MrVauxs** [comment] 2024-08-28 10:12
Cant replicate the damage issue.
![chrome_6xP1YiokLt](https://github.com/user-attachments/assets/8edd1edb-fbd7-4954-8a50-31519e9e63e3)

**Closed by MrVauxs** 2024-08-28 10:12 UTC
Labels: bug

**Comment by ChasarooniZ** [comment] 2024-08-28 21:46
Yeah it started working for me on the newer update not sure why
